a = float(input('Podaj pierwsza liczbe '))
b = float(input('Podaj druga liczbe '))
print('Suma liczb wynosi', a + b)
print('Różnica liczb wynosi', a - b)
print('Iloczyn liczb wynosi', a * b)
print('Iloraz liczb wynosi', a / b)
print('Potega liczb wynosi', a ** b)
print('Reszta z dzielenia modulo liczb wynosi', a % b)
print('Całkowita czesc z dzielenia liczb wynosi', a // b)
